### ISSUE TITLE
Gitignore in root is configured for a VS project

### ISSUE THREAD

**Issue by jwittner** [microsoft/MSBuildForUnity#7]
Should probably simplify or remove the .gitignore in the root folder as it's a bit expansive and targeted to VS rather than the hierarchy you have.

**Comment by ryantrem** [comment]
Yea, I used the VS one at the root because I expect this repo to have VS projects for other things (like NuGet packages with build extensions, including custom MSBuild tasks). Then I used the Unity one within the Unity project in the MSBuildProjectBuilder folder. Alternatively, we could just put the .gitignore for VS projects inside VS project directories we add in the future. I don't feel strongly about it, but I think if it gets removed now, it will come back in some directory later.

**Comment by jwittner** [comment]
Right, we've occasionally ran into this type of VS/Unity ignore file at the root causing unexpected things to be ignored in other places and so have moved to a best practice of putting them at the root of the context they were designed for. So as you say, each VS Project directory, would have a file like this, but never at the root of these kind of multiple 'project' repos itself.
